export const POSITIONS = {
  "Secretary-General": ["Secretary-General","Authorisation Level 7","Executive Operations Board","Board of Directors","Extended Board of Directors"],
  "Deputy Secretary-General": ["Deputy Secretary-General","Authorisation Level 7","Executive Operations Board","Board of Directors","Extended Board of Directors"],
  "Chef de Cabinet": ["Chef de Cabinet","Authorisation Level 7","Executive Operations Board","Board of Directors","Extended Board of Directors"],
  "Senior Advisor to the Secretariat": ["Senior Advisor to the Secretariat","Authorisation Level 7","Executive Operations Board","Board of Directors","Extended Board of Directors"],
  "Director-General": ["Director-General","Authorisation Level 7","Executive Operations Board","Board of Directors","Extended Board of Directors"],
  "Under Secretary-General (DSS)": ["Under Secretary-General (DSS)","Authorisation Level 6","Board of Directors","Extended Board of Directors","Department for Safety and Security"],
  "Under Secretary-General (DMSPC)": ["Under Secretary-General (DMSPC)","Authorisation Level 6","Board of Directors","Extended Board of Directors","Department of Management Strategy, Policy and Compliance"],
  "Under Secretary-General (IC)": ["Under Secretary-General (IC)","Authorisation Level 6","Board of Directors","Extended Board of Directors","International Court"],
  "Under Secretary-General (DGACM)": ["Under Secretary-General (DGACM)","Authorisation Level 6","Board of Directors","Extended Board of Directors","Department of General Assembly and Conference Management"],
  "Under Secretary-General (DCOS)": ["Under Secretary-General (DCOS)","Authorisation Level 6","Board of Directors","Extended Board of Directors","Department of Communications and Operational Support"],
  "Assistant Secretary-General (DSS)": ["Assistant Secretary-General (DSS)","Authorisation Level 5","Extended Board of Directors","Department for Safety and Security"],
  "Assistant Secretary-General (DMSPC)": ["Assistant Secretary-General (DMSPC)","Authorisation Level 5","Extended Board of Directors","Department of Management Strategy, Policy and Compliance"],
  "Assistant Secretary-General (IC)": ["Assistant Secretary-General (IC)","Authorisation Level 5","Extended Board of Directors","International Court"],
  "Assistant Secretary-General (DGACM)": ["Assistant Secretary-General (DGACM)","Authorisation Level 5","Extended Board of Directors","Department of General Assembly and Conference Management"],
  "Assistant Secretary-General (DCOS)": ["Assistant Secretary-General (DCOS)","Authorisation Level 5","Extended Board of Directors","Department of Communications and Operational Support"],
  "Director Safety": ["Director Safety","Authorisation Level 4","Department for Safety and Security"],
  "Director Security": ["Director Security","Authorisation Level 4","Department for Safety and Security"],
  "Director Management Strategy": ["Director Management Strategy","Authorisation Level 4","Department of Management Strategy, Policy and Compliance"],
  "Director Policy and Compliance": ["Director Policy and Compliance","Authorisation Level 4","Department of Management Strategy, Policy and Compliance"],
  "President of the International Court": ["President of the International Court","Authorisation Level 4","International Court"],
  "President of the General Assembly": ["President of the General Assembly","Authorisation Level 4","Department of General Assembly and Conference Management"],
  "Director Communications": ["Director Communications","Authorisation Level 4","Department of Communications and Operational Support"],
  "Director Operational Support": ["Director Operational Support","Authorisation Level 4","Department of Communications and Operational Support"],
  "Deputy Director Safety": ["Deputy Director Safety","Authorisation Level 3","Department for Safety and Security"],
  "Deputy Director Security": ["Deputy Director Security","Authorisation Level 3","Department for Safety and Security"],
  "Deputy Director Management Strategy": ["Deputy Director Management Strategy","Authorisation Level 3","Department of Management Strategy, Policy and Compliance"],
  "Deputy Director Policy and Compliance": ["Deputy Director Policy and Compliance","Authorisation Level 3","Department of Management Strategy, Policy and Compliance"],
  "Vice-President of the International Court": ["Vice-President of the International Court","Authorisation Level 3","International Court"],
  "Vice-President of the General Assembly": ["Vice-President of the General Assembly","Authorisation Level 3","Department of General Assembly and Conference Management"],
  "Deputy Director Communications": ["Deputy Director Communications","Authorisation Level 3","Department of Communications and Operational Support"],
  "Deputy Director Operational Support": ["Deputy Director Operational Support","Authorisation Level 3","Department of Communications and Operational Support"],
  "Judge of the International Court": ["Judge of the International Court","Authorisation Level 2","International Court"],
  "Secretary of the General Assembly": ["Secretary of the General Assembly","Authorisation Level 2","Department of General Assembly and Conference Management"],
  "Registrar of the International Court": ["Registrar of the International Court","Authorisation Level 1","International Court"],
  "Member of the General Assembly": ["Member of the General Assembly","Authorisation Level 1","Department of General Assembly and Conference Management"],
  "Founder": ["Founder","Authorisation Level 7"],
  "CO | Official Account": ["CO | Official Account","Authorisation Level 7"],
  "Bot Developer": ["Bot Developer","Authorisation Level 7"],
};

export const ALL_MANAGED_ROLES = [...new Set([...Object.values(POSITIONS).flat(), 'Verified', 'CO | Staff', 'CO Staff'])];

export function getAuthLevelRole(level) {
  return `Authorisation Level ${level}`;
}
