import { config } from 'dotenv';
config();

export const STAFF_HQ_ID = process.env.STAFF_HQ_ID;
export const NETWORK_SERVER_IDS = (process.env.NETWORK_SERVER_IDS || '').split(',').filter(Boolean);
export const ALL_SERVER_IDS = [
  ...(STAFF_HQ_ID ? [STAFF_HQ_ID] : []),
  ...NETWORK_SERVER_IDS
];
export const SUSPENDED_ROLE_ID = process.env.SUSPENDED_ROLE_ID;
export const UNDER_INVESTIGATION_ROLE_ID = process.env.UNDER_INVESTIGATION_ROLE_ID;
export const APPEALS_SERVER_ID = process.env.APPEALS_SERVER_ID;
export const LOG_CHANNEL_ID = process.env.LOG_CHANNEL_ID;
export const COMMAND_LOG_CHANNEL_ID = process.env.COMMAND_LOG_CHANNEL_ID;
export const SUPERUSER_IDS = (process.env.SUPERUSER_IDS || '').split(',').filter(Boolean);
export const BOT_TOKEN = process.env.DISCORD_BOT_TOKEN;

// Re-export moderation log channel IDs from dedicated channels config
export {
  MOD_LOG_CHANNEL_ID,
  BAN_UNBAN_LOG_CHANNEL_ID,
  GBAN_UNGBAN_LOG_CHANNEL_ID,
  SUSPEND_UNSUSPEND_LOG_CHANNEL_ID,
  TERMINATE_LOG_CHANNEL_ID,
  STRIKE_LOG_CHANNEL_ID,
  INFRACTIONS_CASES_LOG_CHANNEL_ID,
  INVESTIGATION_LOG_CHANNEL_ID,
  PURGE_SCRIBE_LOG_CHANNEL_ID,
  VERIFY_UNVERIFY_LOG_CHANNEL_ID,
  DM_LOG_CHANNEL_ID,
  BRAG_LOG_CHANNEL_ID,
  STAFF_LOG_CHANNEL_ID,
  USER_LOG_CHANNEL_ID,
  NID_LOG_CHANNEL_ID,
  MESSAGE_DELETE_LOG_CHANNEL_ID,
  MESSAGE_EDIT_LOG_CHANNEL_ID,
  FULL_MESSAGE_LOGS_CHANNEL_ID,
  AUTH_OVERRIDE_LOG_CHANNEL_ID,
  COOLDOWN_LOG_CHANNEL_ID,
  MASS_UNBAN_LOG_CHANNEL_ID,
  ROLE_CREATE_LOG_CHANNEL_ID,
  ROLE_DELETE_LOG_CHANNEL_ID,
  ROLE_UPDATE_LOG_CHANNEL_ID,
  ROLE_PERMISSION_LOG_CHANNEL_ID,
  MEMBER_ROLE_ADD_LOG_CHANNEL_ID,
  MEMBER_ROLE_REMOVE_LOG_CHANNEL_ID,
  ROLE_ALL_LOG_CHANNEL_ID,
} from './config/channels.js';

export const OFFICIAL_BYPASS_IDS = ['878775920180228127', '1355367209249148928'];
